### PR TITLE
Add support for GNU's named variadics for macros.

### PR DESCRIPTION
**Pull request by jwnhy**
As mentioned in #164, named_variadics like `#define(x...) x` is widely used in projects like the Linux kernel.

This PR adds support for this feature.

- Options and exceptions.
This PR adds a `BOOST_WAVE_SUPPORT_GNU_NAMED_VARIADICS_PLACEMARKERS` and 
`support_option_named_variadics = 0x100000`.

When the macro is **enabled**, but the runtime option is **not**, it throws `bad_define_statement_named_va_args`, to remind the user to enable the option.
When the macro is **disabled**, it just reports `ill_formed.`

> I haven't figured out a way to inform the user that he/she needs to enable the macro and recompile for this feature to work...

- Lexer part.
I modified the lexer so it accept construct like `(ch_p(T_IDENTIFIER) >> *ppsp >> ch_p(T_ELLIPSIS))`, then, I used `token_node_d` to *compress* all these node into one, and `access_node_d` to modify the node information to `T_GNU_NAMED_VARIADIC`.

This helps deal with later replacement and expansion.
> Keeping all the nodes makes `(x, y...)` and `(x, y, ...)` indistinguishable in the later phases, as the `T_COMMA` does not generate any node.
> Unless we re-visit the original token seq in the later process,which leads to an egg-chicken problem.

- Expansion part.
I re-use most of the original codes.

- Testing
I have run some basic examples to ensure this feature works as expected.
The original test suite also passed, except for the one failure `t_5_007.cpp` that was introduced in #214, which I guess it's my local `libc` issue.

Let me know if there is any issue.

### CODE REVIEW

**Comment by jwnhy** [comment]
I was worried about the validity checks around this feature.
After some digging, I have the following observation.

- It seems we don't need to modify the code in [here](https://github.com/boostorg/wave/blob/46bd710ada96c642008a3e6bb387f6738376d758/include/boost/wave/util/cpp_iterator.hpp#L1714) as it looks better if we prevent the usage of `__VA_ARGS__` even if the user has enabled the named variadics.
- The duplicate parameters `#define dup(x,x...)` are handled in [here](https://github.com/boostorg/wave/blob/7ce8b53d9dc56a9c0b9a8855f26003e6b174301f/include/boost/wave/util/cpp_macromap.hpp#L389).

So, I guess the validity checking code *probably* does not have to be added for named variadics?

Also, is there a dependency system for the compilation options?

For now, all `NAMED_VARIADICS` is guarded by `VARIADICS`, so if `VARIADICS` is not enabled, `NAMED_VARIADICS` is ignored.
A thing that would happen is that a user might only enable `NAMED_VARIADICS` without `VARIADICS`. This causes a compilation error if the user tries something like `need_named_variadics(ctx.get_language())`

I added a warning for that issue.

**Comment by jefftrull** [comment]
I haven't had an opportunity to review the code yet (currently traveling) but this will definitely need tests.

You can either add to one of the existing variadic macro tests, or create a new one (particularly if different command line options are required, e.g. whatever activates the gcc extensions mode).

AFAIK the best documentation on the various test features are found in the test driver code [here](https://github.com/boostorg/wave/blob/ef14767aec712d6d342dc598fbb1432236d930c8/test/testwave/testwave_app.cpp#L431). I often start by finding a similar test to the one I need to write under `test/testwave/testfiles`.

**Comment by jwnhy** [comment]
> I haven't had an opportunity to review the code yet (currently traveling) but this will definitely need tests.
> 
> You can either add to one of the existing variadic macro tests, or create a new one (particularly if different command line options are required, e.g. whatever activates the gcc extensions mode).
> 
> AFAIK the best documentation on the various test features are found in the test driver code [here](https://github.com/boostorg/wave/blob/ef14767aec712d6d342dc598fbb1432236d930c8/test/testwave/testwave_app.cpp#L431). I often start by finding a similar test to the one I need to write under `test/testwave/testfiles`.

Sure, thank you for the advice, sorry I am occupied by some other tasks.

Will find a time to add some tests.
